name: Build and Deploy web app
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          deno install -A --unstable -n deno-create-react-app https://deno.land/x/create_react_app/mod.ts
      - run: |
          cd ./src/app
          deno-create-react-app build
          cp ./robots.txt ./dist/build/
      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: src/app/dist/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}
